---
- name: Install Helm
  hosts: all

  tasks:
  - name: Get helm installation script
    get_url:
      dest: /tmp/helm-install.sh
      url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3

  - name: Install helm from helper script
    command:
      cmd: >
        bash /tmp/helm-install.sh
      creates: /usr/local/bin/helm
