---

- name: Install k3s+Calico
  hosts: all

  tasks:
  - name: Get k3s installer script
    get_url:
      url: https://get.k3s.io
      dest: /tmp/k3s-install.sh

  - name: Install k3s via helper script
    command:
      cmd: >
        sh /tmp/k3s-install.sh
        server
        --datastore-endpoint="mysql://root:@tcp(localhost:3306)/k3s"
      creates: /usr/local/bin/k3s-uninstall.sh
    environment:
      K3S_KUBECONFIG_MODE: '644'
      INSTALL_K3S_EXEC: >
        --flannel-backend=none
        --cluster-cidr=192.168.0.0/16
        --disable-network-policy
        --disable=traefik

  - name: Install Calico
    command:
      cmd: >
        kubectl create
        -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml
    register: calico_install_out
    failed_when:
      - calico_install_out.rc != 0
      - calico_install_out.stderr is not search('namespaces "tigera-operator" already exists')
    changed_when:
      - calico_install_out.stdout is search('deployment.apps/tigera-operator created')

  - name: Create Calico Resources
    command:
      cmd: >
        kubectl create
        -f https://projectcalico.docs.tigera.io/manifests/custom-resources.yaml
    register: calico_resources_out
    failed_when:
      - calico_resources_out.rc != 0
      - calico_resources_out.stderr is not search('installations.operator.tigera.io "default" already exists')
    changed_when:
      - calico_resources_out.stdout is search('installation.operator.tigera.io/default created')

  - name: Enable kubectl completions
    lineinfile:
      insertafter: EOF
      line: command -v kubectl >/dev/null && source <(kubectl completion ${SHELL##*/})
      state: present
      path: .bashrc
