---

- name: Install Rancher
  hosts: all

  vars:
    rancher_namespace: 'cattle-system'
    rancher_release: 'stable'
    cert_manager_version: 'v1.7.1'
    rancher_hostname: 'rancher.my.org'
    rancher_admin_password: 'admin'
    rancher_version: '2.6.5'

  tasks:
    - name: Create Rancher Namespace
      command:
        cmd: >
          kubectl create namespace '{{ rancher_namespace }}'
      register: rancher_namespace_out
      failed_when:
        - rancher_namespace_out.rc != 0
        - rancher_namespace_out.stderr is not search( 'AlreadyExists' )
      changed_when:
        - rancher_namespace_out.stderr is not search( 'AlreadyExists' )

    - name: Add helm repositories
      command:
        cmd: >
          helm repo add
          {{ item.chart }}
          {{ item.uri }}
      with_items:
        - {chart: 'rancher-{{ rancher_release }}', uri: 'https://releases.rancher.com/server-charts/{{ rancher_release }}'}
        - {chart: 'jetstack', uri: 'https://charts.jetstack.io'}
      register: helm_repo_out
      changed_when:
        - helm_repo_out.stdout is not search('skipping')

    - name: Update helm repositories
      command:
        cmd: helm repo update

    - name: Install cert-manager
      command:
        cmd: >
          helm install
          cert-manager jetstack/cert-manager
          --namespace cert-manager
          --create-namespace
          --version {{ cert_manager_version }}
          --set installCRDs=true
      environment:
        KUBECONFIG: '/etc/rancher/k3s/k3s.yaml'
      register: cert_manager_install_out
      failed_when:
        - cert_manager_install_out.rc != 0
        - cert_manager_install_out.stderr is not search('cannot re-use a name that is still in use')
      changed_when:
        - cert_manager_install_out.stderr is not search('cannot re-use a name that is still in use')

    - name: Install Rancher
      command:
        cmd: >
          helm install rancher rancher-{{ rancher_release }}/rancher
          --namespace cattle-system
          --set hostname={{ rancher_hostname }}
          --set bootstrapPassword={{ rancher_admin_password }}
          --version {{ rancher_version }}
      environment:
        KUBECONFIG: '/etc/rancher/k3s/k3s.yaml'
      register: rancher_install_out
      failed_when:
        - rancher_install_out.rc != 0
        - rancher_install_out.stderr is not search('cannot re-use a name that is still in use')
      changed_when:
        - rancher_install_out.stdout is search('Rancher Server has been installed.')
